services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ="Europe/Bucharest"