services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80
      - 8000:443
    volumes:
      - ~/.aspnet/https:/https:ro
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - TZ="Europe/Bucharest"