name: "tempradar-api"
services:
  api:
    image: tempradar-api:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: https://+:443
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${CERTIFICATE_PASSWORD}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionString: Server=sqldata;Database=Tempradar;User Id=sa;Password="${SQL_SERVER_PASSWORD}";TrustServerCertificate=true;
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: "${SQL_SERVER_PASSWORD}"
      ACCEPT_EULA: "Y"
volumes:
  sqlvolume: